shared:
  annotations:
    screwdriver.cd/timeout: 2880
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
  environment:
    MYSQL_HOST: 20.222.144.239
    MYSQL_USER: test
    MYSQL_PASSWD: test
    MYSQL_DB: test
    TABLE_NUM: 4
    TABLE_SIZE: 1000000
    INNODB_BUFFER_POOL_SIZE: 134217728 
    INNODB_IO_CAPACITY: 200
    LOW: 2
    MEDIUM: 4
    HIGH: 6
    TEST_DURATION: 300
    TEST_WORKLOAD_001_LOW: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${LOW} --time=${TEST_DURATION} oltp_read_write run
    TEST_WORKLOAD_001_MEDIUM: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${MEDIUM} --time=${TEST_DURATION} oltp_read_write run
    TEST_WORKLOAD_001_HIGH: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${HIGH} --time=${TEST_DURATION} oltp_read_write run
    TEST_WORKLOAD_002_LOW: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${LOW} --time=${TEST_DURATION} oltp_write_only run
    TEST_WORKLOAD_002_MEDIUM: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${MEDIUM} --time=${TEST_DURATION} oltp_write_only run
    TEST_WORKLOAD_002_HIGH: sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${TABLE_NUM} --table_size=${TABLE_SIZE} --threads=${HIGH} --time=${TEST_DURATION} oltp_write_only run
jobs:
   run_test:
    steps:
     - install-pip: |
         apt-get -y update
         apt-get install -y python3-pip
     - install-libraries: |
         pip install --upgrade pip
         pip install -r requirements.txt
     - python: python3 exporter.py -f ${SD_ARTIFACTS_DIR}/metrics.csv
