shared:
  annotations:
    screwdriver.cd/timeout: 2880
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
  environment:
    MYSQL_HOST: 20.222.144.239
    MYSQL_USER: test
    MYSQL_PASSWD: test
    MYSQL_DB: test
    DEF_TABLE_NUM: 4
    DEF_TABLE_SIZE: 1000000
    DEF_INNODB_BUFFER_POOL_SIZE: 134217728 
    DEF_INNODB_IO_CAPACITY: 200
    DEF_THREAD_NUM: 2
    LOW: 2
    MEDIUM: 4
    HIGH: 6
    DEF_TEST_DURATION: 300
    SLEEP_DURATION: 80
    WORKLOAD_READ_WRITE: oltp_read_write
    WORKLOAD_WRITE_ONLY: oltp_write_only
    WORKLOAD_READ_ONLY: oltp_read_only

jobs:
   run_test:
    steps:
     - constant: |
         LOGINFO="${MYSQL_HOST} ${MYSQL_USER} ${MYSQL_PASSWD} ${MYSQL_DB}"
         DEF_TEST_PARAMETER="${DEF_TABLE_NUM} ${DEF_TABLE_SIZE} ${DEF_THREAD_NUM} 5 ${WORKLOAD_READ_WRITE}"
         DEF_INNODB_PARAMETER="${DEF_INNODB_BUFFER_POOL_SIZE} ${DEF_INNODB_IO_CAPACITY}"
         echo ${LOGINFO}
     - install-pip: |
         apt-get -y update
         apt-get install -y python3-pip
     - install-libraries: |
         pip install --upgrade pip
         pip install -r requirements.txt
     - test: |
         chmod u+x workload.sh
         ./workload.sh ${LOGINFO} ${DEF_TEST_PARAMETER} ${DEF_INNODB_PARAMETER} "metrics.csv"
     - sysbench-download: wget -qO - https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | bash
     - sysbench-deploy: apt-get install -y sysbench
     - sysbench-verify: sysbench --help
     - client-install: apt-get install -y default-mysql-client
     - conn-test: mysql -u ${MYSQL_USER} -p${MYSQL_PASSWD} -h ${MYSQL_HOST} -e "show variables like 'hostname';" 
     - db-param-set: |
         mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWD} -e "set global innodb_buffer_pool_size=${DEF_INNODB_BUFFER_POOL_SIZE}; set global innodb_io_capacity=${DEF_INNODB_IO_CAPACITY}"
         mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWD} -e "show variables like 'innodb_buffer_pool_size'; show variables like 'innodb_io_capacity';"
     - db-create: mysql -u ${MYSQL_USER} -p${MYSQL_PASSWD} -h ${MYSQL_HOST} -e "drop database if exists ${MYSQL_DB}; create database ${MYSQL_DB};"
     - data-load: |
         sysbench --db-driver=mysql --mysql-host=${MYSQL_HOST} --mysql-user=${MYSQL_USER} --mysql-password=${MYSQL_PASSWD} --mysql-db=${MYSQL_DB} --tables=${DEF_TABLE_NUM} --table_size=${DEF_TABLE_SIZE} --threads=${DEF_THREAD_NUM} oltp_common prepare
         sleep 120
     - exec-read-write-workload: |
         WORKLOAD=${WORKLOAD_READ_WRITE}

         FILENAME=${SD_ARTIFACTS_DIR}/metrics1low.csv
         THREAD_NUM=2
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")

         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics1mid.csv
         THREAD_NUM=4
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics1high.csv
         THREAD_NUM=6
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}
     - exec-write-only-workload: |
         WORKLOAD=${WORKLOAD_WRITE_ONLY}

         FILENAME=${SD_ARTIFACTS_DIR}/metrics2low.csv
         THREAD_NUM=2
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")

         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics2mid.csv
         THREAD_NUM=4
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics2high.csv
         THREAD_NUM=6
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}
     - exec-read-only-workload: |
         WORKLOAD=${WORKLOAD_READ_ONLY}

         FILENAME=${SD_ARTIFACTS_DIR}/metrics3low.csv
         THREAD_NUM=2
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")

         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics3mid.csv
         THREAD_NUM=4
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}


         FILENAME=${SD_ARTIFACTS_DIR}/metrics3high.csv
         THREAD_NUM=6
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${DEF_TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}
     - exec-small-table-workload: |
         FILENAME=${SD_ARTIFACTS_DIR}/metrics4small.csv
         TABLE_SIZE=100
         THREAD_NUM=6
         TEST_PARAMETER=("${DEF_TABLE_NUM}" "${TABLE_SIZE}" "${THREAD_NUM}" "${DEF_TEST_DURATION}" "${WORKLOAD}")
         
         ./workload.sh ${LOGINFO} ${TEST_PARAMETER} ${DEF_INNODB_PARAMETER} ${FILENAME}
         sleep ${SLEEP_DURATION}
