acc_metric_name: "mean_average_precision_at_r"

# architecture
hidden_units:
    - 70
    - 70
    - 40

# dataloader options
batch_size: 128
num_workers: 8
valid_split: 0.1

# trainer options
epochs: 100

# optimizer
lr: 0.002
betas:
    - 0.9
    - 0.999
final_lr: 0.001
gamma: 0.01
eps: 1e-8
weight_decay: 1e-9

# schedular
scheduler_step_size: 16
schedular_gamma: 0.3
